name: Second Workflow

on: push

jobs:
  first-job:
    name: check everything
    runs-on: ubuntu-18.04
    steps:
    - name: Check out source repository
      uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with: 
        python-version: '3.8'
    - name: Install flake8
      run: pip install flake8
    - name: Install mypy
      run: pip install mypy
    - name: Install isort
      run: pip install isort
    - name: Use Flake8
      run: flake8 scrape_google.py --count --statistics --max-line-length 300
    - name: Use mypy
      run: mypy scrape_google.py --show-error-codes --disable-error-code import
    - name: Use isort
      run: isort scrape_google.py -c --line-length 300
      

